name: GuardDog

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'PyPI package name to scan'
        required: true
        type: string

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      # contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install GuardDog
        run: pip install guarddog

      - run: guarddog pypi scan ${{ inputs.package_name }}
