name: Test Job Python

on:
  push:
    branches:
      - 'main'

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
    - name: copy single file
      run: python src/copy_aws_to_gcs.py tripdata ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} citibike_trip_history_temp --aws_file JC-202203-citibike-tripdata.csv.zip
