name: Test Job Python

on:
  push:
    branches:
      - 'main'

jobs:
  test_job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Install python libraries
      run: pip install boto3

    - name: copy single file
      run: python src/copy_aws_to_gcs.py tripdata ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} cse-6242-sp22-nyatl citibike_trip_history_temp --aws_file JC-202203-citibike-tripdata.csv.zip
